services:
  - type: web
    name: quran-project-api
    env: php
    plan: free
    buildCommand: ""
    startCommand: php -S 0.0.0.0:10000 -t .
    envVars:
      DB_HOST: localhost
      DB_USER: root
      DB_PASS: ""
      DB_NAME: quran_project
